[character]
format = "[Î»](fg:purple) "

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 1

[hostname]
ssh_only = false

[python]
python_binary = "python3"

[username]
show_always = true
